# Generated by: Sean McNellis (seanmcn)
#
# Copyright © Microsoft Corporation.  All Rights Reserved.
# This code released under the terms of the 
# Microsoft Public License (MS-PL, http://opensource.org/licenses/ms-pl.html.)
# Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment. 
# THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE. 
# We grant You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form of the Sample Code, provided that. 
# You agree: 
# (i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded; 
# (ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; 
# and (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits, including attorneys’ fees, that arise or result from the use or distribution of the Sample Code 

Function Create-CrmUser
{
    param
    (   
        [PSObject]$User,
        [String]$DomainName
    )

    $businessUnitName = If($User.Department -ne $null) {$User.Department} Else {$organizationName}
    $domainName = $DomainName + "\" + $User.SamAccountName

    $businessUnit = Get-CrmRecords -EntityLogicalName businessunit -FilterAttribute name -FilterOperator eq -FilterValue $businessUnitName -Fields businessunitid
    
    If($businessUnit.CrmRecords.Count -eq 0)
    {
        Write-Error "Business Unit $businessUnitName does not exist"
        return
    }
    Else
    {
        $businessUnitId = $businessUnit.CrmRecords[0].businessunitid.Guid
        $User.BusinessUnitId = $businessUnitId

        $crmUser = Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute domainname -FilterOperator eq -FilterValue $domainName -Fields domainname,isdisabled
    
        If($crmUser.CrmRecords.Count -eq 0)
        {
            Write-Output "Creating CRM User $domainName"

            $systemUserId = New-CrmRecord -EntityLogicalName systemuser `
            -Fields @{"domainname"=$domainName;"firstname"=$User.GivenName;`
            "lastname"=$User.SurName;"businessunitid"=(New-CrmEntityReference -EntityLogicalName businessunit -Id $businessUnitId);`
            "homephone"=If($User.HomePhone -ne $null) { $User.HomePhone } Else { "" };`
            "mobilephone"=If($User.MobilePhone -ne $null) { $User.MobilePhone } Else { "" };`
            "address1_postalcode"=If($User.PostalCode -ne $null) { $User.PostalCode } Else { "" };`
            "address1_city"=If($User.PostalCode -ne $null) { $User.PostalCode } Else { "" };`
            "address1_country"=If($User.Country -ne $null) { $User.Country } Else { "" };`
            "address1_stateorprovince"=If($User.State -ne $null) { $User.State } Else { "" };`            
            "address1_line1"=If($User.StreetAddress -ne $null) { $User.StreetAddress } Else { "" };` 
            "jobtitle"=If($User.Title -ne $null) { $User.Title } Else { "" }}

            $User.SystemUserId = $systemUserId            
        }
        Else
        {
            If($crmUser.CrmRecords[0].isdisabled_Property.Value -eq $False)
            {
                Write-Output "CRM User $domainName already exists"
                $User.SystemUserId = $crmUser.CrmRecords[0].systemuserid.Guid
            }
            Else
            {
                Write-Output "CRM User $domainName already exists but disabled state"
            }
        }
    }    
}

Function Assign-CrmUserSecurityRole
{
    param
    (   
        [PSObject]$User,
        [String]$SecurityRoleName
    )

    $domainName = $User.SamAccountName
    $systemUserId = $User.SystemUserId.Value
    $businessUnitId = $User.BusinessUnitId.Value

    $fetch = @"
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" no-lock="true">
  <entity name="role">
    <attribute name="roleid" />
    <filter type="and">
      <condition attribute="name" operator="eq" value="{0}" />
      <condition attribute="businessunitid" operator="eq" value="{1}" />
    </filter>
  </entity>
</fetch>
"@

    $fetch = $fetch -F $SecurityRoleName, $businessUnitId
    $securityRole = Get-CrmRecordsByFetch -Fetch $fetch

    If($securityRole.CrmRecords.Count -eq 0)
    {
        Write-Error "SecurityRole $SecurityRoleName does not exist"
        return
    }
    Else
    {
        Write-Output "Assign $SecurityRoleName role to $domainName"
        $securityRoleId = $securityRole.CrmRecords[0].roleid.Guid
        Add-CrmSecurityRoleToUser -UserId $systemUserId -SecurityRoleId $securityRoleId
    }    
}

# Script parameters #
$ouPath = "<LDAP path i.e.) OU=CrmUsers,DC=contoso,DC=local>"
$domainName = "<DomainName i.e.) contoso>"

$organizationName = "<organization name> i.e.) contoso>"
$serverUrl ="<CRM Server URL i.e.) http://crmserver:5555>"
$crmAdminUser = "<CRM admin account i.e.) contoso\administrator>"
$crmAdminPassword = ConvertTo-SecureString -String "<password>" -AsPlainText -Force

$securityRoleName = "<SecurityRole Name i.e.) Salesperson>"
# Script parameters #

Write-Output "Connecting to CRM OnPremise as $crmAdminUser"
$crmCred = New-Object System.Management.Automation.PSCredential ($crmAdminUser,$crmAdminPassword) 
Try
{
    # Refer to https://msdn.microsoft.com/en-us/library/dn756303.aspx for more detail 
    $global:conn = Get-CrmConnection -OrganizationName $organizationName -ServerUrl $serverUrl -Credential $crmCred -ErrorAction Stop
}
Catch
{
    throw 
}

Write-Output "Loading Users from particular OU"
$users = Get-ADUser -SearchBase $ouPath -Filter * -Properties *

Write-Output "Create Crm User on Dynamics CRM OnPremise"
$users | % {Create-CrmUser -User $_ -DomainName $domainName}

Write-Output "Assign Security Role to Crm User"
$users | % {Assign-CrmUserSecurityRole -User $_ -SecurityRoleName $SecurityRoleName}

Write-Output "Completed"