can you convert this from azure pipeline yaml to github action yaml which will achieve the same outcome? 
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls
  displayName: 'List all files/directories in root'

- script: find . -name '*.pshproj' -delete
  displayName: 'Delete pshproj files'

- script: find . -name '*.pssproj' -delete
  displayName: 'Delete pssproj files'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/Microsoft.Xrm.Data.PowerShell'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Microsoft.Xrm.Data.PowerShell'
    CleanTargetFolder: true
    OverWrite: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      echo $(Build.SourcesDirectory)/Microsoft.Xrm.Data.PowerShell
      ls $(Build.SourcesDirectory)/Microsoft.Xrm.Data.PowerShell
      #Publish-Module -NuGetApiKey $(GalleryKey) -Path $(Build.SourcesDirectory)/Microsoft.Xrm.Data.PowerShell -verbose -whatif
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
